name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (if any)
        run: echo "No build needed for static HTML"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # The root of your static site
          publish_branch: gh-pages
